### ISSUE TITLE
SIntesis

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Edwin38H#1]
[Sintesis gestion de proyetos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Edwin38H/files/9569463/Sintesis.gestion.de.proyetos.pdf)

**Comment by carlos-chrs** [comment]
Revisado 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
